export const GAME_CONFIG = {
  room: {
    minPlayers: 2,
    maxPlayers: 6,
    codeLength: 6,
    hostTimeoutMs: 8_000,
  },
  maze: {
    width: 151,
    height: 151,
    cellSize: 2,
    wallHeight: 3.1,
    majorZones: 50,
    minimumZoneCells: 8,
    connectorWidthCells: 3,
    partitionDensity: 0.85,
    pillarDensity: 0.34,
    pillarClusterChance: 0.55,
    stubWallDensity: 0.7,
    alcoveDensity: 0.45,
    doorJogChance: 0.5,
    bonusConnectorChance: 0.35,
    ceilingJitter: 0.45,
    openness: 0.62,
    occlusion: 0.68,
    repetition: 0.72,
    spawnSeparationMeters: 90,
  },
  player: {
    radius: 0.38,
    walkSpeed: 5.2,
    sprintSpeed: 8,
    ghostSpeed: 9,
    eyeHeight: 1.65,
  },
  network: {
    simulationHz: 20,
    inputHz: 20,
    snapshotHz: 10,
    interpolationMs: 100,
  },
  enemy: {
    roamSpeed: 1.9,
    searchSpeed: 2.2,
    investigateSpeed: 2.6,
    chaseSpeed: 3.4,
    acceleration: 4.5,
    chaseAcceleration: 8,
    turnRate: 3.1,
    chaseTurnRate: 6.4,
    radius: 0.42,
    detectionRange: 18,
    hearingRange: 9,
    attackRange: 2.4,
    contactRange: 1.05,
    contactSecondsToDown: 0.7,
    memorySeconds: 4,
    searchDuration: 9,
    searchRadiusCells: 6,
    fullStrengthDistance: 12,
    groupedDistance: 4,
    minScale: 0.28,
  },
  stomp: {
    proximityFactor: 0.9,
    maxEnemyScale: 0.35,
    range: 2.5,
    confirmationSeconds: 0.75,
  },
} as const;

export const MAP_SIZE_DIMENSIONS = {
  small: 71,
  medium: 111,
  large: GAME_CONFIG.maze.width,
} as const;

export type GameConfig = typeof GAME_CONFIG;
